### ISSUE TITLE
Suggest a Better Lexer Generator!

### ISSUE THREAD

**Issue by QuestionPython** [kumakichi/go-calculator#1]
Hello,

Flex(GoLex)

i think is better then you use from golex (flex), its fast and easy.

Main: https://github.com/cznic/golex/
Sample: https://github.com/cznic/golex/tree/master/calc - https://godoc.org/github.com/cznic/ebnf2y
Comment : golex -h(generate lexer) , goyacc -h(generate yacc)

I'm waiting for you...
I hope this is helpful to do as soon as possible.

please do it.
Thanks a lot.

**Comment by kumakichi** [comment]
Er,I'm doing some other projects recently,so i don't think i have time to do this in these days

**Comment by QuestionPython** [comment]
6 days ago you say : 
>i don't think i have time to do this in these days
